language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev"
install:
  - "pip install -r requirements.txt"
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install coveralls"
  - "pip install ."
script:
    coverage run --source phylogemetric -m py.test
after_success:
    coveralls
